# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DocumentTypePrefix(UniversalBaseModel):
    credit_note: typing.Optional[str] = None
    delivery_note: typing.Optional[str] = None
    invoice: typing.Optional[str] = None
    purchase_order: typing.Optional[str] = None
    quote: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
