# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .financing_offer import FinancingOffer
from .wc_business_status import WcBusinessStatus


class FinancingOffersResponse(UniversalBaseModel):
    offers: typing.List[FinancingOffer] = pydantic.Field()
    """
    A list of financing offers extended to the business.
    """

    business_status: WcBusinessStatus = pydantic.Field()
    """
    The business's onboarding status.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
